SELECT * FROM CM_INDICADOR;
SELECT * FROM CM_CONFIGURACION;
SELECT * FROM CM_INDICADOR_CALCULO_CACHE;
SELECT * FROM CM_INDICADOR_CALCULO;
SELECT * FROM CM_ANALITICAINCIDENCIA;

DROP TABLE CM_ANALITICAINCIDENCIA;


CREATE TABLE CM_INDICADOR (
    ID_INDICADOR NUMBER(38,0),
    DEFINICION VARCHAR2(1000),
    NOMBRE VARCHAR2(1000),
    OBJETIVO VARCHAR2(1000),
    ID_TIPO NUMBER(38,0),
    SENTIDO VARCHAR2(1000),
    ID_FRECUENCIA NUMBER(38,0),
    ID_ESTADO NUMBER(38,0)
);

INSERT INTO CM_INDICADOR (ID_INDICADOR, DEFINICION, NOMBRE, OBJETIVO, ID_TIPO, SENTIDO, ID_FRECUENCIA, ID_ESTADO) VALUES (1, 'Primer indicador', 'Primer', '1-ObjIndicador', 01, '1sentido', 001, 0011 );
INSERT INTO CM_INDICADOR (ID_INDICADOR, DEFINICION, NOMBRE, OBJETIVO, ID_TIPO, SENTIDO, ID_FRECUENCIA, ID_ESTADO) VALUES (2, 'Segund indicador', 'Segundo', '2-ObjIndicador', 02, '2sentido', 002, 0022 );
INSERT INTO CM_INDICADOR (ID_INDICADOR, DEFINICION, NOMBRE, OBJETIVO, ID_TIPO, SENTIDO, ID_FRECUENCIA, ID_ESTADO) VALUES (3, 'Tercer indicador', 'Tercer', '3-ObjIndicador', 03, '3sentido', 003, 0033 );


CREATE TABLE CM_CONFIGURACION (
    ID_CONFIGURACION NUMBER(38,0),
    DESCRIPCION VARCHAR2(1000),
    ABREVIATURA VARCHAR2(1000),
    ID_CATEGORIA NUMBER(38,0)
);

INSERT INTO CM_CONFIGURACION (ID_CONFIGURACION, DESCRIPCION, ABREVIATURA, ID_CATEGORIA) VALUES (1, 'Primer indicador','PriInd', 01 );
INSERT INTO CM_CONFIGURACION (ID_CONFIGURACION, DESCRIPCION, ABREVIATURA, ID_CATEGORIA) VALUES (2, 'Segund indicador','SecInd', 02 );
INSERT INTO CM_CONFIGURACION (ID_CONFIGURACION, DESCRIPCION, ABREVIATURA, ID_CATEGORIA) VALUES (3, 'Tercer indicador','TerInd', 03 );



CREATE TABLE CM_INDICADOR_CALCULO_CACHE (
    ID_INDICADOR_CACHE NUMBER(38,0),
    ID_INDICADOR_CALCULO NUMBER(38,0),
    VALOR VARCHAR2(4000),
    FECHA DATE
);


INSERT INTO CM_INDICADOR_CALCULO_CACHE (ID_INDICADOR_CACHE, ID_INDICADOR_CALCULO, VALOR, FECHA)
VALUES (1, 1001, 'Valor de prueba 1', TO_DATE('2023-11-02', 'YYYY-MM-DD'));

INSERT INTO CM_INDICADOR_CALCULO_CACHE (ID_INDICADOR_CACHE, ID_INDICADOR_CALCULO, VALOR, FECHA)
VALUES (2, 1002, 'Valor de prueba 2', TO_DATE('2023-11-03', 'YYYY-MM-DD'));

INSERT INTO CM_INDICADOR_CALCULO_CACHE (ID_INDICADOR_CACHE, ID_INDICADOR_CALCULO, VALOR, FECHA)
VALUES (3, 1003, 'Valor de prueba 3', TO_DATE('2023-11-04', 'YYYY-MM-DD'));


CREATE TABLE CM_INDICADOR_CALCULO (
    ID_INDICADOR_CALCULO NUMBER(38,0),
    CALCULO VARCHAR2(4000),
    FUENTE VARCHAR2(1000),
    SEMAFORIZACION VARCHAR2(1000),
    ID_UNIDAD_MEDIDA NUMBER(38,0),
    ID_NIVEL_DETALLE NUMBER(38,0),
    ID_TIPO_REPRESENTACION NUMBER(38,0),
    TEXTO_INTELIGENTE VARCHAR2(4000),
    ID_INDICADOR NUMBER(38,0),
    FECHA_HORA_ACTUALIZACION DATE
);


INSERT INTO CM_INDICADOR_CALCULO (ID_INDICADOR_CALCULO, CALCULO, FUENTE, SEMAFORIZACION, ID_UNIDAD_MEDIDA, ID_NIVEL_DETALLE, ID_TIPO_REPRESENTACION, TEXTO_INTELIGENTE, ID_INDICADOR, FECHA_HORA_ACTUALIZACION)
VALUES (1, 'Cálculo de prueba 1', 'Fuente de prueba 1', 'SemafORIZACIÓN 1', 1001, 2001, 3001, 'Texto inteligente 1', 5001, TO_DATE('2023-11-02', 'YYYY-MM-DD'));

INSERT INTO CM_INDICADOR_CALCULO (ID_INDICADOR_CALCULO, CALCULO, FUENTE, SEMAFORIZACION, ID_UNIDAD_MEDIDA, ID_NIVEL_DETALLE, ID_TIPO_REPRESENTACION, TEXTO_INTELIGENTE, ID_INDICADOR, FECHA_HORA_ACTUALIZACION)
VALUES (2, 'Cálculo de prueba 2', 'Fuente de prueba 2', 'SemafORIZACIÓN 2', 1002, 2002, 3002, 'Texto inteligente 2', 5002, TO_DATE('2023-11-03', 'YYYY-MM-DD'));

INSERT INTO CM_INDICADOR_CALCULO (ID_INDICADOR_CALCULO, CALCULO, FUENTE, SEMAFORIZACION, ID_UNIDAD_MEDIDA, ID_NIVEL_DETALLE, ID_TIPO_REPRESENTACION, TEXTO_INTELIGENTE, ID_INDICADOR, FECHA_HORA_ACTUALIZACION)
VALUES (3, 'Cálculo de prueba 3', 'Fuente de prueba 3', 'SemafORIZACIÓN 3', 1003, 2003, 3003, 'Texto inteligente 3', 5003, TO_DATE('2023-11-04', 'YYYY-MM-DD'));


  CREATE TABLE CM_ANALITICAINCIDENCIA (
   "ID_INCIDECNIA" NUMBER(38,0),
   "SECTOR" VARCHAR2(100 BYTE),
   "TIPO_INCIDENCIA" VARCHAR2(500 BYTE), 
	"ESTADO" VARCHAR2(100 BYTE), 
	"FECHA_INCIDENCIA" VARCHAR2(100 BYTE), 
	"FECHA_REGISTRO" VARCHAR2(100 BYTE), 
	"CRITICIDAD" VARCHAR2(100 BYTE), 
	"DESCRIPCION_INCIDENCIA" VARCHAR2(4000 BYTE), 
	"AFECTACION" VARCHAR2(4000 BYTE), 
	"CAUSA_INCIDENCIA" VARCHAR2(4000 BYTE), 
	"FUENTE_INFORMACION" VARCHAR2(1000 BYTE), 
	"DIRECCION_AFECTACION" VARCHAR2(1000 BYTE), 
	"DIRECCION_DEPARTAMENTO" VARCHAR2(100 BYTE), 
	"DIRECCION_PROVINCIA" VARCHAR2(100 BYTE), 
	"DIRECCION_DISTRITO" VARCHAR2(100 BYTE), 
	"DIRECCION_UBIGEO" VARCHAR2(6 BYTE), 
	"LATITUD" VARCHAR2(100 BYTE), 
	"LONGITUD" VARCHAR2(100 BYTE), 
	"OFICINA_REGIONAL" VARCHAR2(100 BYTE), 
	"OFICINA_REGIONAL_PROFESIONAL" VARCHAR2(100 BYTE), 
	"AFECTACION_NUM_FAMILIAS" NUMBER(38,0), 
	"AFECTACION_NUM_PERSONAS" NUMBER(38,0), 
	"AFECTACION_VIVIENDAS" NUMBER(38,0), 
	"AFECTACION_NUM_FALLECIDOS" NUMBER(38,0), 
	"ANALISIS_POST" VARCHAR2(4000 BYTE), 
	"URL_FOTO01" VARCHAR2(100 BYTE), 
	"URL_FOTO02" VARCHAR2(100 BYTE), 
	"URL_FOTO03" VARCHAR2(100 BYTE), 
	"URL_FOTO04" VARCHAR2(100 BYTE), 
	"INFORME" VARCHAR2(100 BYTE)
   );
   
INSERT INTO CM_ANALITICAINCIDENCIA ("ID_INCIDECNIA", "SECTOR", "TIPO_INCIDENCIA", "ESTADO", "FECHA_INCIDENCIA", "FECHA_REGISTRO", "CRITICIDAD", "DESCRIPCION_INCIDENCIA", "AFECTACION", "CAUSA_INCIDENCIA", "FUENTE_INFORMACION", "DIRECCION_AFECTACION", "DIRECCION_DEPARTAMENTO", "DIRECCION_PROVINCIA", "DIRECCION_DISTRITO", "DIRECCION_UBIGEO", "LATITUD", "LONGITUD", "OFICINA_REGIONAL", "OFICINA_REGIONAL_PROFESIONAL", "AFECTACION_NUM_FAMILIAS", "AFECTACION_NUM_PERSONAS", "AFECTACION_VIVIENDAS", "AFECTACION_NUM_FALLECIDOS", "ANALISIS_POST", "URL_FOTO01", "URL_FOTO02", "URL_FOTO03", "URL_FOTO04", "INFORME")
VALUES (1, 'Sector 1', 'Tipo de Incidencia 1', 'Estado 1', '2023-11-02', '2023-11-02', 'Criticidad 1', 'Descripción de la Incidencia 1', 'Afectación 1', 'Causa de la Incidencia 1', 'Fuente de Información 1', 'Dirección de Afectación 1', 'Departamento 1', 'Provincia 1', 'Distrito 1', 'Ubi 1', 'Latitud 1', 'Longitud 1', 'Oficina Regional 1', 'Oficina Regional Profesional 1', 10, 50, 20, 5, 'Análisis Post 1', 'URL 1', 'URL 2', 'URL 3', 'URL 4', 'Informe 1');

INSERT INTO CM_ANALITICAINCIDENCIA ("ID_INCIDECNIA", "SECTOR", "TIPO_INCIDENCIA", "ESTADO", "FECHA_INCIDENCIA", "FECHA_REGISTRO", "CRITICIDAD", "DESCRIPCION_INCIDENCIA", "AFECTACION", "CAUSA_INCIDENCIA", "FUENTE_INFORMACION", "DIRECCION_AFECTACION", "DIRECCION_DEPARTAMENTO", "DIRECCION_PROVINCIA", "DIRECCION_DISTRITO", "DIRECCION_UBIGEO", "LATITUD", "LONGITUD", "OFICINA_REGIONAL", "OFICINA_REGIONAL_PROFESIONAL", "AFECTACION_NUM_FAMILIAS", "AFECTACION_NUM_PERSONAS", "AFECTACION_VIVIENDAS", "AFECTACION_NUM_FALLECIDOS", "ANALISIS_POST", "URL_FOTO01", "URL_FOTO02", "URL_FOTO03", "URL_FOTO04", "INFORME")
VALUES (2, 'Sector 2', 'Tipo de Incidencia 2', 'Estado 2', '2023-11-03', '2023-11-03', 'Criticidad 2', 'Descripción de la Incidencia 2', 'Afectación 2', 'Causa de la Incidencia 2', 'Fuente de Información 2', 'Dirección de Afectación 2', 'Departamento 2', 'Provincia 2', 'Distrito 2', 'Ubi 2', 'Latitud 2', 'Longitud 2', 'Oficina Regional 2', 'Oficina Regional Profesional 2', 15, 70, 25, 8, 'Análisis Post 2', 'URL 5', 'URL 6', 'URL 7', 'URL 8', 'Informe 2');

INSERT INTO CM_ANALITICAINCIDENCIA ("ID_INCIDECNIA", "SECTOR", "TIPO_INCIDENCIA", "ESTADO", "FECHA_INCIDENCIA", "FECHA_REGISTRO", "CRITICIDAD", "DESCRIPCION_INCIDENCIA", "AFECTACION", "CAUSA_INCIDENCIA", "FUENTE_INFORMACION", "DIRECCION_AFECTACION", "DIRECCION_DEPARTAMENTO", "DIRECCION_PROVINCIA", "DIRECCION_DISTRITO", "DIRECCION_UBIGEO", "LATITUD", "LONGITUD", "OFICINA_REGIONAL", "OFICINA_REGIONAL_PROFESIONAL", "AFECTACION_NUM_FAMILIAS", "AFECTACION_NUM_PERSONAS", "AFECTACION_VIVIENDAS", "AFECTACION_NUM_FALLECIDOS", "ANALISIS_POST", "URL_FOTO01", "URL_FOTO02", "URL_FOTO03", "URL_FOTO04", "INFORME")
VALUES (3, 'Sector 3', 'Tipo de Incidencia 3', 'Estado 3', '2023-11-04', '2023-11-04', 'Criticidad 3', 'Descripción de la Incidencia 3', 'Afectación 3', 'Causa de la Incidencia 3', 'Fuente de Información 3', 'Dirección de Afectación 3', 'Departamento 3', 'Provincia 3', 'Distrito 3', 'Ubi 3', 'Latitud 3', 'Longitud 3', 'Oficina Regional 3', 'Oficina Regional Profesional 3', 20, 90, 30, 10, 'Análisis Post 3', 'URL 9', 'URL 10', 'URL 11', 'URL 12', 'Informe 3');

   
